[project]
name = "image-styler"
version = "0.1.0"
description = "AI-powered image styling with Streamlit"
requires-python = ">=3.12"
dependencies = [
    "streamlit",
    "replicate",
    "python-dotenv",
    "pillow",
    "ipykernel>=6.29.5",
]
